package fi.vm.sade.valintalaskenta.tulos.roles;

public class ValintojenToteuttaminenRole {
  public static final String READ_UPDATE_CRUD =
      "hasAnyRole('ROLE_APP_VALINTOJENTOTEUTTAMINEN_READ','ROLE_APP_VALINTOJENTOTEUTTAMINEN_READ_UPDATE','ROLE_APP_VALINTOJENTOTEUTTAMINEN_CRUD')";
  public static final String UPDATE_CRUD =
      "hasAnyRole('ROLE_APP_VALINTOJENTOTEUTTAMINEN_READ_UPDATE','ROLE_APP_VALINTOJENTOTEUTTAMINEN_CRUD')";
  public static final String CRUD = "hasAnyRole('ROLE_APP_VALINTOJENTOTEUTTAMINEN_CRUD')";
  public static final String OPH_CRUD =
      "hasAnyRole('ROLE_APP_VALINTOJENTOTEUTTAMINEN_CRUD_1.2.246.562.10.00000000001')";
  public static final String ROLE_VALINTOJENTOTEUTTAMINEN_TULOSTENTUONTI =
      "ROLE_APP_VALINTOJENTOTEUTTAMINEN_TULOSTENTUONTI";
}
