sudo: required

services:
- docker

cache:
  directories:
  - $HOME/.m2

env:
  global:
  # ARTIFACTORY_USERNAME
  - secure: "K+ZoESCQovFz4NQ1Xkt7EcLwMfOlKfKUuOGrLJeeHnPe3gi5RCUqppsoFM1u4gtVrb+iUvFNekZls9j7BkV32wq7Nw6raLAHdHYH+w4UQzInPuMg38U8m6cNejavWqwf+Ru4iswTb1aNnmAPYopBTimS1D3v9+o1Tlwt3biJmYmJdadzHK8U7dD8spscrE1T82DmQoqgeaRYzQsQpyUxXXKCSJBbUZhpEzfisO3uS/xq0VDxsX8OvJxwXayY7bGEyFgOZPtGMjpXJgFbH3BOgITwKUdrbSUyFHyTYVWeElRwWroZ4YhIbUFefmxl+p2jvXTU0SYRVegbFhEXmHc702Q/dFeBSmNwdElgYroaU4EtF0KXZdU6ILITLcOAKSUO5rvdn5GpaHOrGoPKVlN+O2261ZvNPK0+K1Juh/U4RmwEx//5wp6ligGFOsp/cin3leDxjZ8Z7ep3iuVr0wVaxUGJim+rZ/HnG0D2CKE4ZeXVJ7NYjksnHmFVcb7dc2cvdbw4uJDBiGd/g0TWJdJh2ytgcNI8NZIf1+281HzvcAl2+VmcehUFeoqi72tfoKePTTNBADL65emC8j6l06TqWSmGBYUZTRprxpZaBrVXcAVu+6iTIK0tgaT+5JYIwaS8FlsWIWMlRstur6KN8qnNYIm/gYlsazd7GTOj8Z2lekM="
  # ARTIFACTORY_PASSWORD
  - secure: "hme8O9MZaoocVQI58xap/3SAgeWOq7kzVfOGoOM0yQGBORW2IFQWOi+WpUmU93SlnGhehgkLf4F6fbMwhF7BSyo9pkNO7ikgWpntyQce0n2ROhchJhKHZrAzwWWMdSvHAgjitgpVCEVnw7wP1c90+czsMk1ZJ0q8hF7xHN09ehfRqtW5b/P2AYlRHNwnB8KjfCbZCxwyYFSlRJPC30HX+WWcK3ZyDgIb7TqKDVc3nCE0zVIYXUM0eKE+LcSb/NM1wDcL3CwT+vrKUBC2wp+selmCUHzHD7LULXid/exE945MLShI5tzAocejG8BXw/vIsVh55jNKq7hTcYgMGBmZbgIdpqc4Ruj36VEZkjOLYLBuDzzgKEywC5xpPQvx5Laj7bIb46bGpBegW9VfUbiuGg/Bp8AZjns0WgPz1SYz0kl1wo4KT59cgmaLI9Ho5bGH9kymBssWZEJ9A+D+wDF/1mE7YnGvkaONLoWBkIW1J68H24iD+2Fj48cA/XWT3xif30qR1qNcFKOqh5zJ1+QwuLesDPL80Xp44Sg5GEfdhG0A9uB3hjD/swxcQNfiPt/N5caVfn+BTlTIS6S/HSd8YfOUjk3lOEgrSL87Osb00MoPq1ZS9K6jrD4Qg1Xq15MhzoS1/i5J1olDoFO1BNlUo1XQDR7UdN7MkA6opTzimkM="
  # AWS_ACCESS_KEY_ID
  - secure: "WU1nrsoFNMPN8PFhwHYaNTK7OWjK8AdMFh3CL899X0u4FMXT39f6WuF40VIHKR9vUcVbz4sHpHVwNAq8dARaqVXDGyhray+dphz+EGAikprCK8YpjSFnBXDAKkgxAScWfFe5eRqLesNr9GsXzU3UBFCv3C4dXzn1nYWnshdmhNJi+F1KhKOBOh+RVtEn+2TxhnyjkUcYZdb5NQAoiZiI/meXJEwg/3pbMJV3Ih+Y+EPem6TM1DUT3Ij/lzFrSGnqn8ryBdDZo4w2c7nhkueOTM0T1gcUYYM+7NtmSoHFVZl57SMFr8s445vnt0VUP4r6vf7Haqyn/dfhyswFdol/8NEOwKUlrtyuZrXmPsMDijlB1Lofct+5Zj8Uy2aYLbfctGjRiZNNwxKuRD+8pCz/xT18zWYdP70L4gcfoCB3gr4aETeEOIhlq90C1MYwUwirrEIDD+3f2W2FEfxIqqtfuotbdGyjsDHwols2r6A+IjBeRanRpRIELxmDr/6fAzy5f+YCOaShKdMWM1/pWWO4YOMfYHgnWHZQY5xpUYSe4NsYrTo1RYPDBWCs7qlRJKR4h6NyPj9G4XwIVVnwnLiUiKmPqqomUzXFqGrov9miq+xhxUk4Z/RNKuP8SHW2HSSgXgG8tUAS12Ats9dIozEfyGf7gWY5Nl/sGD+Z+fRH4Js="
  # AWS_SECRET_ACCESS_KEY
  - secure: "FrU1OBtkdDOKNuF2wn5mx2ErJkEy/vZhmFtufPm/jMRrIAnIG54wdyo22gNieDX2rYfkdUcpwvfmiF+oXPRtGneV/RGPYU1vpfskIHKWC+USUIQhh/DstorTk/GFHQQfJU3xdVczHnTVyJjyPT6ciwSQ7yxxDhhkdbt3l9snHGG3vrzU4aUYIPGISTGvB9F7yfc4eoO7WGbg0EDZSoctuEXDMlJtGSyamxiblNxh/vLbzDMPUUh55GyJm/E6Hv22QbLCIDJHua+Gz1o4kXCvXwAwrb7C4h+BqJHkbr5CYMKHJerz934Q1QRLtC3x10lKXqQ/D0RyH+tb4Y1P5XzN2NCIRjsoyNoQT0WGxhmw5Rx3CeL51qEkeb9JDAos/am3H/4DGdA9P8Pdu4agUYzX7me78gjIlvohvOSONQcO1V+EhnGZHkDNO+M4vfc+Te7rY/ZNlfCM4VWwRD8iJA8v2XbBtOgDKSsvyHBGnzuiUnc2RM2bI8kkqJv2eywlObPRfo8+lNrpRW9mC3IFi8zpIfwiBDW6gmFZkHzGk6LPgeo+ub+K6c0CxbdYtt+5l/+tluYObHM6grQzCIqc/RCpkrF3UVecs7Xv97iCp4fAWkVhU59FwveOpnWq1qRZutQl1g4UA+gsCfJdOhMG4GSr1FXSNUNRirMpLDaAM/oy1Hs="

jobs:
  include:
    - language: java
      jdk: openjdk8
      install:
        - git clone https://github.com/Opetushallitus/ci-tools.git
        - source ci-tools/common/setup-tools.sh
        - sudo sh -c "printf '\n%s penaali.hard.ware.fi\n' $(dig +short artifactory.opintopolku.fi|head -n1) >> /etc/hosts"
        - export ARTIFACT_NAME="valintalaskenta"
      script:
        - mvn clean install -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}
        - mv valintalaskenta-laskenta-service/target/valintalaskenta-laskenta-service-*allinone.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar
        - cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/
        - export BASE_IMAGE="baseimage-fatjar:master"
        - ./ci-tools/common/pull-image.sh
        - ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME
      deploy:
        - provider: script
          script: mvn deploy -pl fi.vm.sade.valintaperusteet:valintalaskenta,valintalaskenta-laskenta-api,valintalaskenta-tulos-api,valintalaskenta-domain,valintalaskenta-tulos-service -DskipTests --settings ci-tools/common/maven-settings.xml
          skip_cleanup: true
          on:
            branch: master
        - provider: script
          script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
          on:
            all_branches: true
    - language: java
      openjdk: openjdk11
      script:
        - ./bin/run-spotless-in-travis.sh
