<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="valintalaskentaTulosService" 
                  targetNamespace="http://valintalaskenta.tulos.service.sade.vm.fi/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
                  xmlns:tns="http://valintalaskenta.tulos.service.sade.vm.fi/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                  
    <wsdl:types>
        <xsd:schema targetNamespace="http://valintalaskenta.tulos.service.sade.vm.fi/">
            <xsd:import namespace="http://valintalaskenta.tulos.service.sade.vm.fi/types" schemaLocation="valintalaskentatulosService.xsd" />
        </xsd:schema>
    </wsdl:types>


</wsdl:definitions>