spring:
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true

valintalaskenta-laskenta-service:
  postgresql:
    url: jdbc:postgresql://localhost:5555/valintalaskenta
    user: app
    password: app
    maxactive: 10
    maxwait: 3000
    leakdetectionthresholdmillis: 1800000
    driver: org.postgresql.Driver
  organisaatio-service:
    url:

valintalaskenta:
  uses-ssl-proxy: false
  enable-siirtotiedosto-service: true

logging:
  level:
    root: info
    org.springframework: warn
    org.springframework.security: warn
    org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration: warn
    fi.vm.sade.auditlog.Audit: info
    fi.vm.sade.java_utils.security.OpintopolkuCasAuthenticationFilter: warn
    org.apache.http.client.protocol.ResponseProcessCookies: error
    org.springframework.web: info
    org.hibernate: info
    com.github.dockerjava: info

root:
  organisaatio:
    oid: ""

aws:
  region: eu-west-1
  bucket:
    name: ""
    oldversionname: ""
  siirtotiedosto:
    bucket-name: testi-siirtotiedostot
    bucket-target-role-arn: arn:aws:iam::xxxxxxxxxxxx:role/opintopolku-s3-cross-account-role
    max-valinnanvihe-count-in-file: 10000
    max-hakemus-count-in-file: 20000
