<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="valintalaskentaService"
                  targetNamespace="http://valintalaskenta.service.sade.vm.fi"
                  xmlns:tns="http://valintalaskenta.service.sade.vm.fi"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:valintalaskenta="http://valintalaskenta.service.sade.vm.fi/messages">

        <wsdl:types>
            <xsd:schema targetNamespace="http://valintalaskenta.service.sade.vm.fi">
                <xsd:import namespace="http://valintalaskenta.service.sade.vm.fi/messages" schemaLocation="valintalaskenta.xsd" />
            </xsd:schema>
        </wsdl:types>

        <wsdl:message name="laske">
            <wsdl:part name="parameters" element="valintalaskenta:laske" />
        </wsdl:message>
        <wsdl:message name="laskeVastaus">
            <wsdl:part name="parameters" element="valintalaskenta:laskeVastaus" />
        </wsdl:message>
        <wsdl:message name="paasykokeet">
            <wsdl:part name="parameters" element="valintalaskenta:paasykokeet" />
        </wsdl:message>
        <wsdl:message name="paasykokeetVastaus">
            <wsdl:part name="parameters" element="valintalaskenta:paasykokeet" />
        </wsdl:message>

        <wsdl:portType name="ValintalaskentaService">
            <wsdl:documentation>Palvelu valintalaskennan suorittamiseen</wsdl:documentation>
            <wsdl:operation name="laske">
                <wsdl:input message="tns:laske" />
                <wsdl:output message="tns:laskeVastaus" />
            </wsdl:operation>
            <wsdl:operation name="paasykokeet">
                <wsdl:input message="tns:paasykokeet" />
                <wsdl:output message="tns:paasykokeetVastaus" />
            </wsdl:operation>
        </wsdl:portType>

        <wsdl:binding name="ValintalaskentaServiceSoapBinding" type="tns:ValintalaskentaService">
            <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
            <wsdl:operation name="laske">
                <soap:operation soapAction="" style="document" />
                <wsdl:input>
                    <soap:body use="literal" />
                </wsdl:input>
                <wsdl:output>
                    <soap:body use="literal" />
                </wsdl:output>
            </wsdl:operation>
            <wsdl:operation name="paasykokeet">
                <soap:operation soapAction="" style="document" />
                <wsdl:input>
                    <soap:body use="literal" />
                </wsdl:input>
                <wsdl:output>
                    <soap:body use="literal" />
                </wsdl:output>
            </wsdl:operation>
        </wsdl:binding>

        <wsdl:service name="ValintalaskentaService">
            <wsdl:port name="ValintalaskentaServicePort" binding="tns:ValintalaskentaServiceSoapBinding">
                <soap:address location="http://localhost:8181/cxf/valintalaskentaService" />
            </wsdl:port>
        </wsdl:service>

</wsdl:definitions>